# Generated by Django 2.1.4 on 2018-12-27 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='like_num',
            new_name='liked_num',
        ),
    ]
